# Task 3: Join Orders and Shipments

- Join the orders and shipments datasets using `order_id`.
- Calculate the mean order amount per customer using the joined table.
- Calculate the mean order amount per customer using the original orders table.
- Compare the results and determine which calculation is correct.

In [1]:
import pandas as pd

orders = pd.read_csv("../data/orders.csv")
shipments = pd.read_csv("../data/shipments.csv")

In [3]:
display(orders.head())
display(shipments.head())

  order_id customer_id  amount
0    O1000        C106      26
1    O1001        C105      48
2    O1002        C103     155
3    O1003        C100      38
4    O1004        C103     136

  order_id tracking
0    O1000  O1000-1
1    O1001  O1001-1
2    O1001  O1001-2
3    O1002  O1002-1
4    O1003  O1003-1

In [15]:
joined = orders.merge(
    shipments,
    on="order_id",
    how="left",
    validate="one_to_many"
)

In [16]:
joined.head(10)

  order_id customer_id  amount   company  quarter tracking
0    O1000        C106      26  Umbrella  2024-Q4  O1000-1
1    O1001        C105      48  Umbrella  2023-Q3  O1001-1
2    O1001        C105      48  Umbrella  2023-Q3  O1001-2
3    O1002        C103     155    Globex  2025-Q2  O1002-1
4    O1003        C100      38      Acme  2023-Q4  O1003-1
5    O1003        C100      38      Acme  2023-Q4  O1003-2
6    O1004        C103     136    Globex  2023-Q3  O1004-1
7    O1004        C103     136    Globex  2023-Q3  O1004-2
8    O1004        C103     136    Globex  2023-Q3  O1004-3
9    O1005        C107     144   Soylent  2023-Q4  O1005-1

In [17]:
#average on the joined table
joined_average = joined.groupby('customer_id')['amount'].mean()
#average on the non joined table
regular_average = orders.groupby("customer_id")["amount"].mean()
display(joined_average)
display(regular_average)

customer_id
C100     38.000
C101     62.000
C102    105.000
C103    112.375
C104     33.000
C105     67.625
C106     62.250
C107    106.000
Name: amount, dtype: float64

customer_id
C100     38.00
C101     62.00
C102    105.00
C103    111.60
C104     33.00
C105     67.25
C106     59.50
C107     96.50
Name: amount, dtype: float64

### Task 3 Conclusion

- The mean amount per customer differs between the joined table and the original orders table for some customers.
- This happens because the join is one-to-many. An order can have multiple shipments, so some orders appear multiple times in the joined table.
- When the mean is calculated directly from the joined table, the amount for orders with multiple shipments is counted multiple times.
- The mean calculated from the orders table is correct because each order appears only once, so every order amount is counted once.

In [ ]:
}